### ISSUE TITLE
Bug #1: v-repeat bug?

### ISSUE THREAD

**Issue by JaymanMDev** [YoeriNijs/vienna#1] opened 2021-11-18 10:05 UTC
For some reason a v-repeat block appears underneath the other DOM when rendered despite being above it in the html template.

html: `
    <v-repeat let="{{todo}}" for="{{todoList}}">
      <div>
        {{todo}}
      </div>
    </v-repeat>
    <input value="{{currentTodo}}" onchange="changeTodoValue(e)" />
    <button @click="addTodo">
      Add Todo
    </button>
`

Also, I would love some support for on change events like above. :)

EDIT: I realised that there is a bind event that binds the DOM element to a variable. Neat!

**Comment by YoeriNijs** [comment] 2021-11-18 19:26
Hi!

Thank you for your bug report! Currently, I have found the cause of this issue and planning to release a bugfix soon. Furthermore, I am working on a @change attribute that you can apply to an element. Please stay tuned :)

**Comment by YoeriNijs** [comment] 2021-11-19 15:17
Fixed in 0.1.0 :)

**Closed by YoeriNijs** 2021-11-19 15:17 UTC
Labels: bug
